apiVersion: v1
kind: ServiceAccount
metadata:
  name: rke-nvidia-configurator-svc-account
  namespace: gpu-operator
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rke-nvidia-configurator-cm-role-binding
subjects:
- kind: ServiceAccount
  name: rke-nvidia-configurator-svc-account
  namespace: gpu-operator
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
