# This task should be removed in the long run when we have a better
# build system in place, but for now, force pull in case the tag has
# changed in docker hub
- name: Update all images from docker hub
  shell: >
    crictl image | awk '{print $1}' | xargs -n 1 crictl pull
  become: yes
  when: cm_force_pull_images
  ignore_errors: true

- name: Update Cloudman
  tags:
    - cloudman_setup
    - cloudman_update
  block:
    - name: Create temp file for cloudman helm values
      tempfile:
        state:  file
        suffix: helmvals
      register: temp_helmvals

    - name: Render CloudMan chart custom values file
      template:
        src: cm_chart_values.yml.j2
        dest: "{{ temp_helmvals.path }}"

    - name: Helm install CloudMan
      command: >
        /usr/local/bin/helm upgrade --reset-values --install cloudman galaxyproject/cloudman
        --create-namespace
        --namespace "{{ cm_namespace_name }}"
        {% if cm_chart_version %}
        --version "{{ cm_chart_version }}"
        {% endif %}
        -f "{{ temp_helmvals.path }}"
      ignore_errors: true

    - name: Remove temporary values file
      file:
        path: "{{ temp_helmvals.path }}"
        state: absent
      when: temp_helmvals.path is defined
