- name: Add helm repositories
  tags:
    - cloudman_setup
    - galaxy_setup
    - cloudman_update
    - galaxy_update
  block:
    - name: "Add CloudVE Helm repo: {{ cm_charts_repo }}"
      shell: /usr/local/bin/helm repo add galaxyproject {{ cm_charts_repo }}
      ignore_errors: True

    - name: Update Helm repos
      shell: /usr/local/bin/helm repo update
