- name: Helm install nfs-provisioner
  command: >
    /usr/local/bin/helm install nfs-provisioner stable/nfs-server-provisioner
    --namespace "{{ cm_namespace_name }}"
    --version "0.3.1"
    --set persistence.enabled=true
    --set persistence.storageClass="ebs"
    --set persistence.size="{{ cm_initial_storage_size }}"
    --set storageClass.create=true
    --set storageClass.defaultClass=true
    --set storageClass.reclaimPolicy="Delete"
    --set storageClass.allowVolumeExpansion=true

- name: Helm install RClone for AWS
  command: >
    /usr/local/bin/helm install rclone-csi wunderio/csi-rclone
    --namespace "{{ cm_namespace_name }}"
    --set storageClass.name="rclone"
    --set params.remote="s3"
    --set params.remotePath="{{ rancher_server | replace('.', '-') }}-gvl-data"
    --set params.s3-provider="aws"
    --set params.s3-endpoint="https://s3.{{ (cm_initial_cluster_data | b64decode | from_yaml).cloud_config.target.target_zone.region.region_id }}.amazonaws.com"
    --set params.s3-access-key-id="{{ (cm_initial_cluster_data | b64decode | from_yaml).cloud_config.credentials.aws_access_key }}"
    --set params.s3-secret-access-key="{{ (cm_initial_cluster_data | b64decode | from_yaml).cloud_config.credentials.aws_secret_key }}"
  when: kube_cloud_provider == "aws"
  ignore_errors: true
